from pathlib import Path
from datetime import datetime,timedelta
import pandas as pd
def get_last_complete_month_end():
    today=datetime.now();first_of_month=today.replace(day=1);last_month_end=first_of_month-timedelta(days=1);return last_month_end.strftime("%Y-%m-%d")
def get_training_start_date(end_date_str,years=20):
    end=pd.Timestamp(end_date_str);start=end-timedelta(days=years*365+450);return start.strftime("%Y-%m-%d")
CACHE_DIR="./data_cache";CBOE_DATA_DIR="./CBOE_Data_Archive";ENABLE_TRAINING=True;TRAINING_YEARS=20;RANDOM_STATE=42
TRAINING_END_DATE=get_last_complete_month_end();TRAINING_START_DATE=get_training_start_date(TRAINING_END_DATE,TRAINING_YEARS)
CALIBRATION_WINDOW_DAYS=252;CALIBRATION_DECAY_LAMBDA=0.125;MIN_SAMPLES_FOR_CORRECTION=50;MODEL_VALIDATION_MAE_THRESHOLD=0.20
CALIBRATION_PERIOD=("2023-01-01","2024-06-30");VALIDATION_PERIOD=("2024-07-01","2024-12-31");PRODUCTION_START_DATE="2025-01-01"
TARGET_CONFIG={"horizon_days":5,"horizon_label":"5d","target_type":"log_vix_change","output_type":"vix_pct_change","log_space":{"enabled":True,"description":"Train on log(future_vix/current_vix), convert to % for output"},"movement_bounds":{"floor":-50.0,"ceiling":100.0,"description":"Percentage change bounds (converted from log-space)"}}
CALENDAR_COHORTS={"fomc_period":{"condition":"macro_event_period","range":(-7,2),"weight":1.35,"description":"FOMC meetings, CPI releases, PCE releases, FOMC minutes"},"opex_week":{"condition":"days_to_monthly_opex","range":(-7,0),"weight":1.3,"description":"Options expiration week + VIX futures rollover"},"earnings_heavy":{"condition":"spx_earnings_pct","range":(0.15,1.0),"weight":1.1,"description":"Peak earnings season (Jan, Apr, Jul, Oct)"},"mid_cycle":{"condition":"default","range":None,"weight":1.0,"description":"Regular market conditions"}}
COHORT_PRIORITY=["fomc_period","opex_week","earnings_heavy","mid_cycle"]
MACRO_EVENT_CONFIG={"cpi_release":{"day_of_month_target":12,"window_days":2},"pce_release":{"day_of_month_target":28,"window_days":3},"fomc_minutes":{"days_after_meeting":21,"window_days":2},"fomc_meeting":{"pre_meeting_days":7,"post_meeting_days":2}}
FEATURE_SELECTION_CONFIG={"magnitude_top_n":70,"direction_top_n":96,"cv_folds":5,"protected_features":["is_fomc_period","is_opex_week","is_earnings_heavy"],"correlation_threshold":1,"description":"Feature selection tuned via hyperparameter optimization"}
DIRECTION_CALIBRATION_CONFIG={"enabled":True,"method":"isotonic","min_samples":100,"out_of_bounds":"clip","description":"Calibrate direction probabilities to match true accuracy rates"}
ENSEMBLE_CONFIG={"enabled":True,"reconciliation_method":"weighted_agreement","confidence_weights":{"magnitude":0.35,"direction":0.45,"agreement":0.20},"magnitude_thresholds":{"small":2.0,"medium":5.0,"large":10.0},"agreement_bonus":{"strong":0.15,"moderate":0.08,"weak":0.0},"contradiction_penalty":{"severe":0.25,"moderate":0.15,"minor":0.05},"min_ensemble_confidence":0.50,"actionable_threshold":0.65,"description":"Ensemble combines magnitude + direction with agreement-based confidence"}
XGBOOST_CONFIG={"strategy":"dual_model","cohort_aware":False,"magnitude_params":{"objective":"reg:squarederror","eval_metric":"rmse","max_depth":3,"learning_rate":0.0133,"n_estimators":436,"subsample":0.7409,"colsample_bytree":0.9162,"colsample_bylevel":0.8823,"min_child_weight":8,"reg_alpha":1.1390,"reg_lambda":3.7097,"gamma":0.3023,"early_stopping_rounds":50,"seed":42,"n_jobs":-1},"direction_params":{"objective":"binary:logistic","eval_metric":"logloss","max_depth":5,"learning_rate":0.0419,"n_estimators":481,"subsample":0.8288,"colsample_bytree":0.7644,"min_child_weight":6,"reg_alpha":1.9222,"reg_lambda":3.1447,"gamma":0.4038,"scale_pos_weight":1.1706,"early_stopping_rounds":50,"seed":42,"n_jobs":-1},"regime_thresholds":{"Low Vol":{"threshold":12.0,"min_vix":0,"max_vix":15.57},"Normal":{"threshold":9.0,"min_vix":15.57,"max_vix":23.36},"Elevated":{"threshold":10.0,"min_vix":23.36,"max_vix":31.16},"Crisis":{"threshold":6.0,"min_vix":31.16,"max_vix":100}},"cv_config":{"method":"time_series_split","n_splits":5,"test_size":0.15,"val_size":0.15,"gap":5},"actionable_confidence_threshold":0.70}
MODEL_OBJECTIVES=["magnitude_5d","direction_5d"]
PREDICTION_DB_CONFIG={"db_path":"data_cache/predictions.db","table_name":"forecasts","min_samples_for_calibration":MIN_SAMPLES_FOR_CORRECTION,"schema":{"prediction_id":"TEXT PRIMARY KEY","timestamp":"DATETIME","observation_date":"DATE","forecast_date":"DATE","horizon":"INTEGER","calendar_cohort":"TEXT","cohort_weight":"REAL","prob_up":"REAL","prob_down":"REAL","magnitude_forecast":"REAL","expected_vix":"REAL","feature_quality":"REAL","num_features_used":"INTEGER","current_vix":"REAL","actual_vix_change":"REAL","actual_direction":"INTEGER","direction_error":"REAL","magnitude_error":"REAL","correction_type":"TEXT","features_used":"TEXT","model_version":"TEXT","created_at":"DATETIME","direction_probability":"REAL","direction_prediction":"TEXT","direction_correct":"INTEGER"},"indexes":["CREATE INDEX idx_timestamp ON forecasts(timestamp)","CREATE INDEX idx_observation_date ON forecasts(observation_date)","CREATE INDEX idx_cohort ON forecasts(calendar_cohort)","CREATE INDEX idx_forecast_date ON forecasts(forecast_date)","CREATE INDEX idx_correction_type ON forecasts(correction_type)"]}
ENABLE_TEMPORAL_SAFETY=True
FORWARD_FILL_LIMITS={"daily":5,"weekly":7,"monthly":35,"quarterly":135}
FRED_SERIES_METADATA={"ICSA":{"frequency":"weekly","category":"labor"},"STLFSI4":{"frequency":"weekly","category":"financial_stress"},"DGS1MO":{"frequency":"daily","category":"treasuries"},"DGS3MO":{"frequency":"daily","category":"treasuries"},"DGS6MO":{"frequency":"daily","category":"treasuries"},"DGS1":{"frequency":"daily","category":"treasuries"},"DGS2":{"frequency":"daily","category":"treasuries"},"DGS5":{"frequency":"daily","category":"treasuries"},"DGS10":{"frequency":"daily","category":"treasuries"},"DGS30":{"frequency":"daily","category":"treasuries"},"BAMLH0A0HYM2":{"frequency":"daily","category":"credit_spreads"},"BAMLH0A1HYBB":{"frequency":"daily","category":"credit_spreads"},"BAMLH0A2HYB":{"frequency":"daily","category":"credit_spreads"},"BAMLH0A3HYC":{"frequency":"daily","category":"credit_spreads"},"BAMLC0A0CM":{"frequency":"daily","category":"credit_spreads"},"SOFR":{"frequency":"daily","category":"funding"},"SOFR90DAYAVG":{"frequency":"daily","category":"funding"},"DFF":{"frequency":"daily","category":"fed_rates"},"T10Y2Y":{"frequency":"daily","category":"treasury_spreads"},"T10Y3M":{"frequency":"daily","category":"treasury_spreads"},"T5YIE":{"frequency":"daily","category":"inflation"},"T10YIE":{"frequency":"daily","category":"inflation"},"VIXCLS":{"frequency":"daily","category":"volatility"},"CPIAUCSL":{"frequency":"monthly","category":"inflation"},"CPILFESL":{"frequency":"monthly","category":"inflation"},"PCEPI":{"frequency":"monthly","category":"inflation"},"PCEPILFE":{"frequency":"monthly","category":"inflation"},"UNRATE":{"frequency":"monthly","category":"labor"},"PAYEMS":{"frequency":"monthly","category":"labor"},"UMCSENT":{"frequency":"monthly","category":"sentiment"},"INDPRO":{"frequency":"monthly","category":"production"},"M1SL":{"frequency":"monthly","category":"monetary"},"M2SL":{"frequency":"monthly","category":"monetary"},"WALCL":{"frequency":"weekly","category":"monetary"},"WTREGEN":{"frequency":"weekly","category":"monetary"},"GDP":{"frequency":"quarterly","category":"growth"},"GDPC1":{"frequency":"quarterly","category":"growth"}}
PUBLICATION_LAGS={"^GSPC":0,"^VIX":0,"^VVIX":0,"CL=F":0,"GC=F":0,"DX-Y.NYB":0,"SKEW":0,"VIX3M":0,"VX1-VX2":0,"VX2-VX1_RATIO":0,"CL1-CL2":0,"DX1-DX2":0,"COR1M":0,"COR3M":0,"VXTH":0,"VXTLT":0,"PCCE":0,"PCCI":0,"PCC":0,"DGS1MO":1,"DGS3MO":1,"DGS6MO":1,"DGS1":1,"DGS2":1,"DGS5":1,"DGS10":1,"DGS30":1,"DTWEXBGS":1,"CPIAUCSL":14,"CPILFESL":14,"PCEPI":28,"PCEPILFE":28,"UNRATE":7,"PAYEMS":7,"ICSA":4,"STLFSI4":7,"BAMLH0A0HYM2":1,"BAMLH0A1HYBB":1,"BAMLH0A2HYB":1,"BAMLH0A3HYC":1,"BAMLC0A0CM":1,"SOFR":0,"SOFR90DAYAVG":0,"DFF":1,"T10Y2Y":1,"T10Y3M":1,"T5YIE":1,"T10YIE":1,"VIXCLS":1,"GDP":90,"GDPC1":90,"UMCSENT":14,"INDPRO":14,"M1SL":7,"M2SL":7,"WALCL":4,"WTREGEN":4}
FEATURE_QUALITY_CONFIG={"staleness_penalty":{"none":1.0,"minor":0.95,"moderate":0.80,"severe":0.50,"critical":0.20},"missingness_penalty":{"critical_features":["vix","spx","vix_percentile_21d","spx_realized_vol_21d"],"important_features":["VX1-VX2","SKEW","yield_10y2y","Dollar_Index"],"optional_features":["GAMMA","VPN","BFLY"]},"quality_thresholds":{"excellent":0.95,"good":0.85,"acceptable":0.70,"poor":0.50,"unusable":0.30}}
QUALITY_FILTER_CONFIG={"enabled":True,"min_threshold":0.70,"warn_pct":20.0,"error_pct":50.0,"strategy":"raise"}
REGIME_BOUNDARIES=[0,15.57,23.36,31.16,100];REGIME_NAMES={0:"Low Vol",1:"Normal",2:"Elevated",3:"Crisis"};SKEW_ELEVATED_THRESHOLD=145;CRISIS_VIX_THRESHOLD=31.16
FORECASTING_CONFIG={"horizon_days":TARGET_CONFIG["horizon_days"],"target_type":TARGET_CONFIG["target_type"],"movement_bounds":TARGET_CONFIG["movement_bounds"],"training_end_date":TRAINING_END_DATE,"calibration_period":CALIBRATION_PERIOD,"validation_period":VALIDATION_PERIOD,"production_start_date":PRODUCTION_START_DATE,"enable_training":ENABLE_TRAINING,"random_state":RANDOM_STATE}
VIX_BASE_FEATURES={"mean_reversion":["vix_vs_ma10","vix_vs_ma21","vix_vs_ma63","vix_vs_ma252","vix_bb_position_20d","reversion_strength_21d","reversion_strength_63d","vix_pull_ma21","vix_pull_ma63","vix_stretch_ma21","vix_stretch_ma63","vix_extreme_low_21d","vix_mean_distance_21d"],"dynamics":["vix_ret_1d","vix_ret_5d","vix_ret_10d","vix_ret_21d","vix_vol_10d","vix_vol_21d","vix_vol_63d","vix_velocity_5d","vix_velocity_10d","vix_velocity_21d","vix_zscore_21d","vix_zscore_63d","vix_zscore_252d","vix_momentum_z_10d","vix_momentum_z_21d","vix_accel_5d"],"regimes":["vix_regime","vix_regime_duration","vix_displacement","vix_term_structure"]}
SPX_BASE_FEATURES={"price_action":["spx_ret_1d","spx_ret_5d","spx_ret_10d","spx_ret_21d","spx_ret_63d","spx_vs_ma20","spx_vs_ma50","spx_vs_ma200","spx_momentum_z_10d","spx_momentum_z_21d"],"volatility":["spx_realized_vol_10d","spx_realized_vol_21d","spx_realized_vol_63d","spx_vol_ratio_10_21","spx_vol_ratio_10_63","spx_skew_21d","spx_kurt_21d","bb_position_20d","bb_width_20d"],"technical":["rsi_14","rsi_regime","rsi_divergence","macd","macd_signal","macd_histogram","adx_14","trend_strength"],"ohlc_microstructure":["spx_body_size","spx_range","spx_range_pct","spx_upper_shadow","spx_lower_shadow","spx_close_position","spx_body_to_range","spx_gap","spx_gap_magnitude","spx_upper_rejection","spx_lower_rejection","spx_range_expansion"]}
CROSS_ASSET_BASE_FEATURES={"spx_vix_relationship":["spx_vix_corr_21d","spx_vix_corr_63d","spx_vix_corr_126d","vix_vs_rv_10d","vix_vs_rv_21d","vix_rv_ratio_10d","vix_rv_ratio_21d"]}
CBOE_BASE_FEATURES={"skew_indicators":["SKEW","skew_regime","skew_vs_vix","skew_vix_ratio","skew_displacement"],"put_call_ratios":["pc_equity_inst_divergence","pcc_accel_10d"],"correlation_indices":["COR1M","COR1M_change_21d","COR1M_zscore_63d","COR3M","COR3M_change_21d","COR3M_zscore_63d","cor_term_structure","cor_term_slope_change_21d"],"other_cboe":["VXTH","VXTH_change_21d","VXTH_zscore_63d","vxth_vix_ratio","cboe_stress_composite","cboe_stress_regime"],"bond_volatility":["VXTLT","VXTLT_change_21d","VXTLT_zscore_63d","VXTLT_velocity_10d","VXTLT_acceleration_5d","bond_vol_regime","vxtlt_vix_ratio","vxtlt_vix_spread","VXTLT_percentile_63d","VXTLT_percentile_126d","VXTLT_percentile_252d","VXTLT_vs_ma21","VXTLT_vs_ma63","bond_equity_vol_divergence"]}
FUTURES_FEATURES={"vix_futures":["VX1-VX2","VX1-VX2_change_21d","VX1-VX2_zscore_63d","VX1-VX2_percentile_63d","VX2-VX1_RATIO","VX2-VX1_RATIO_velocity_10d","vx_term_structure_regime","vx_curve_acceleration","vx_term_structure_divergence"],"commodity_futures":["CL1-CL2","CL1-CL2_velocity_5d","CL1-CL2_zscore_63d","oil_term_regime","crude_oil_ret_10d","crude_oil_ret_21d","crude_oil_ret_63d","crude_oil_vol_21d","crude_oil_zscore_63d"],"dollar_futures":["DX1-DX2","DX1-DX2_velocity_5d","DX1-DX2_zscore_63d","dxy_ret_10d","dxy_ret_21d","dxy_ret_63d","dxy_vs_ma50","dxy_vs_ma200","dxy_vol_21d"],"cross_futures":["vx_crude_corr_21d","vx_crude_divergence","vx_dollar_corr_21d","dollar_crude_corr_21d","spx_vx_spread_corr_21d","spx_dollar_corr_21d"]}
META_FEATURES={"regime_indicators":["vix_regime_micro","regime_transition_risk","vol_regime","risk_premium_regime","vol_term_regime","trend_regime","trend_strength","liquidity_stress_composite","liquidity_regime","correlation_regime"],"cross_asset_relationships":["equity_vol_divergence","equity_vol_corr_breakdown","risk_premium_ma21","risk_premium_velocity","risk_premium_zscore","gold_spx_divergence","dollar_spx_correlation"],"rate_of_change":["vix_velocity_3d_pct","vix_jerk_5d","vix_momentum_regime","SKEW_momentum_regime","spx_realized_vol_21d_velocity_3d","spx_realized_vol_21d_acceleration_5d","vix_skew_momentum_divergence"],"percentile_rankings":["vix_percentile_21d","vix_percentile_63d","vix_percentile_126d","vix_percentile_252d","vix_percentile_velocity","vix_extreme_low_63d","vix_extreme_low_252d","SKEW_percentile_21d","SKEW_percentile_63d","SKEW_percentile_126d","SKEW_percentile_velocity","risk_premium_percentile_21d","risk_premium_percentile_63d","risk_premium_percentile_126d","risk_premium_percentile_252d","risk_premium_extreme_low_63d"]}
MACRO_FEATURES={"currencies":["Dollar_Index_lag1","Dollar_Index_zscore_63d"],"volatility_indices":["Bond_Vol_lag1","Bond_Vol_mom_10d","Bond_Vol_mom_21d","Bond_Vol_mom_63d","Bond_Vol_zscore_63d"]}
CALENDAR_FEATURES=["month","day_of_week","day_of_month"]
FEATURE_CONFIG={"base_features":{"vix":VIX_BASE_FEATURES,"spx":SPX_BASE_FEATURES,"cross_asset":CROSS_ASSET_BASE_FEATURES,"cboe":CBOE_BASE_FEATURES,"futures":FUTURES_FEATURES,"macro":MACRO_FEATURES,"meta":META_FEATURES},"calendar_features":CALENDAR_FEATURES,"publication_lags":PUBLICATION_LAGS,"temporal_safety":ENABLE_TEMPORAL_SAFETY}
FEATURE_SELECTION_CV_PARAMS={"n_estimators":132,"max_depth":3,"learning_rate":0.0544,"subsample":0.8044,"colsample_bytree":0.8411}
HYPERPARAMETER_TUNING_CONFIG={"enabled":False,"method":"optuna","n_trials":500,"cv_folds":5,"timeout_hours":24,"magnitude_param_space":{"max_depth":(2,8),"learning_rate":(0.005,0.1),"n_estimators":(100,1000),"subsample":(0.6,1.0),"colsample_bytree":(0.6,1.0),"colsample_bylevel":(0.6,1.0),"min_child_weight":(1,15),"reg_alpha":(0.0,5.0),"reg_lambda":(0.0,10.0),"gamma":(0.0,2.0)},"direction_param_space":{"max_depth":(3,10),"learning_rate":(0.01,0.15),"n_estimators":(100,1000),"subsample":(0.6,1.0),"colsample_bytree":(0.6,1.0),"min_child_weight":(1,15),"reg_alpha":(0.0,5.0),"reg_lambda":(0.0,10.0),"gamma":(0.0,2.0),"scale_pos_weight":(0.8,2.0)},"description":"Hyperparameter optimization with Optuna - run after ensemble implementation"}
